# Generated by Django 4.2.23 on 2025-06-22 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_chatmessage_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='name',
            field=models.CharField(default='_', max_length=255),
        ),
    ]
