# Generated by Django 4.2.23 on 2025-06-22 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='input_tokens',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='output_tokens',
            field=models.IntegerField(default=0),
        ),
    ]
