services:
  frontend:
    build: ./frontend
    ports:
      - "8501:8501"
    volumes:
      - ./frontend:/app
    networks:
      - rag_network

  backend-ui:
    build: ./backend-ui
    ports:
      - "3000:3000"
    volumes:
      - ./backend-ui:/app
      - /app/node_modules
    networks:
      - rag_network

  backend:
    build: ./backend
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - data:/data
    depends_on:
      - db
      - opensearch
    networks:
      - rag_network

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=rag_db
      - POSTGRES_USER=rag_user
      - POSTGRES_PASSWORD=rag_password
    ports:
      - "5432:5432"
    networks:
      - rag_network

  opensearch:
    image: opensearchproject/opensearch:3.0.0
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - "DISABLE_INSTALL_DEMO_CONFIG=false"
      - "DISABLE_SECURITY_PLUGIN=false"
    env_file:
      - .env
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "9200:9200"
      - "9600:9600"
    volumes:
      - opensearch_data:/usr/share/opensearch/data
    networks:
      - rag_network

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:3.0.0
    ports:
      - "5601:5601"
    environment:
      - OPENSEARCH_HOSTS=["https://opensearch:9200"]
      - OPENSEARCH_USERNAME=admin
      - OPENSEARCH_PASSWORD=${OPENSEARCH_INITIAL_ADMIN_PASSWORD}
      - "OPENSEARCH_SSL_VERIFICATIONMODE=none"
    depends_on:
      - opensearch
    networks:
      - rag_network

volumes:
  postgres_data:
  opensearch_data:
  data:

networks:
  rag_network:
    driver: bridge
