apiVersion: apps/v1
kind: Deployment
metadata:
  name: opensearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opensearch
  template:
    metadata:
      labels:
        app: opensearch
    spec:
      containers:
      - name: opensearch
        image: opensearchproject/opensearch:2
        ports:
        - containerPort: 9200
        - containerPort: 9600
        env:
        - name: "discovery.type"
          value: "single-node"
        - name: "OPENSEARCH_JAVA_OPTS"
          value: "-Xms512m -Xmx512m"
        - name: "OPENSEARCH_INITIAL_ADMIN_PASSWORD"
          value: "myStrongPassword123!"
